
spring:
  security:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/stp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath:mappers/*.xml
server:
  port: 8080

flask:
  api:
    url: http://localhost:5000/predict
    url2: http://localhost:5001
